### ISSUE TITLE
Get {{proxyfhirServerUrl}}/Provenance request is not working

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#69]
Hello team,

I'm trying to retrieve the fhir provenance resource using postman.

I'm getting an error stating Could not find Patient Reference Patient/7f1afe3a-2ad0-48cd-bbe6-6d9edf8fb483 in reference fields patient of resource Provenance/d1567109-b1d6-4d68-bc50-20fd9655d48d.
If I use fhir server Url without the proxy and make the same request, I get the correct result for the provenance resource.

This proxy is trying to reference patient/7f1afe3a-2ad0-48cd-bbe6-6d9edf8fb483 in each and every resource. Provenance doesn't have a patient reference field in the FHIR R4 version. 

I'm getting the same error for resources CarePlan, Encounter, and Procedure stating could not find a patient reference
patient/7f1afe3a-2ad0-48cd-bbe6-6d9edf8fb483 in the patient reference field of CarePlan, Encounter, and Procedure Resources. 

I have added fhirUser Claim as per this documentation and used patient/7f1afe3a-2ad0-48cd-bbe6-6d9edf8fb483 in the extensionAttribute. 

Anybody here has any idea about this? I have been stuck on this for a long time.

**Comment by Kedar782** [comment]
@daemel 
Do you have any input on this?
I've been stuck on this for a long time. Do I need to modify the proxy for this?
When I hit the {fhirserverUrlwithoutproxy}/Provenance I get the correct response.
But I'm getting the above error when I hit {fhirserverUrlwithproxy}/Provenance.
For other resources also similar errors are coming for the proxy.
I will really appreciate your help.

**Comment by Kedar782** [comment]
Hello @vohuythao 

No, I have not found any workaround yet. I'm on a tight timeline.
I'm receiving the same error for other resources like CarePlan, Encounter, Goal, and Procedure.
Proxy is trying to locate patient reference in the patient field of the above resources. If I look into Hl7 documentation FHIR version R4, the above resources do not have a patient field.
Also, Have you passed test 7(Multi Patient API) using v2.0?
I'm receiving errors for accessing the resources. When I open my ndjson file and use the access token I get the 500 server response code. I have no idea how to fix it.

**Comment by vohuythao** [comment]
Hello @Kedar782 

You got same issue with me.
I am running the Inferno ONC Certification (g)(10) Standardized API
V.3.3.1
and cannot pass the Test 4 (Single patient API)
I am using Azure API for FHIR and FHIR Proxy
I am stuck at Test 4 and still go to Test 7 yet

You mean v2.0 is the SMART App Lauch 2.0, right?
Thank you

**Comment by vohuythao** [comment]
Hello @daemel 

So sorry for mention you here, but may I know if the Microsoft team has any plan or assign someone to work on this?
We are stucking at this issue for a long time and has a very near deadline

Thank you very much

**Comment by vohuythao** [comment]
Hello @Kedar782 

May I know if you passed the Inferno test 7.2.04

Currently I met this
![image](https://user-images.githubusercontent.com/14121587/204256627-c8a67d71-bead-4c8f-82f2-f738f4ecafa3.png)

I already turn on in the FHIR proxy
FHIRProxy.preprocessors.ONCExportPreProcess
FHIRProxy.postprocessors.ONCExportPostProcess

I go to the proxy function app and check log

Look like the export pre process and post process is already running

![image](https://user-images.githubusercontent.com/14121587/204257092-a7f930a1-57b6-4133-b539-a8b3494cdd10.png)


But it said ""The requested \"export\" operation is not enabled"

Not sure why

Do we need to enable the $export configuration in Azure API for FHIR itself
https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/configure-export-data

Thank you

**Comment by Kedar782** [comment]
@vohuythao 
I have passed the test 7.2.04. Follow this document to enable export on your FHIR Server.
https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/configure-export-data

Please let me know if you passed the rest of the test cases for Multi Patient API. I'm getting errors after the test 7.3.03.
Also, Have you passed the test 4 Single Patient API?

**Comment by sordahl-ga** [comment]
This item should be resolved with commits:
https://github.com/microsoft/fhir-proxy/commit/f0e360fa051c66b9dd34821a8ea2b3b3492e9a8d
https://github.com/microsoft/fhir-proxy/commit/efe9bf9c2bac27348b163e296923f6c0d216955b
https://github.com/microsoft/fhir-proxy/commit/bb757ca31039365b62074d777492342429178737

**Comment by Kedar782** [comment]
@sordahl-ga 
It worked for provenance resource but I'm receiving same errors for resources Goal and Procedure.
Errors are:- 
"entry": [
    {
      "fullUrl": "https://sfp-proxy16248.azurewebsites.net/fhir/Procedure/16b495e0-c8d7-4ea4-8805-ac9a9498321c",
      "resource": {
        "resourceType": "OperationOutcome",
        "id": "c57df443-7625-476e-a7c5-c38bda13ca28",
        "issue": [
          {
            "severity": "warning",
            "code": "forbidden",
            "diagnostics": "Could not find Patient Reference Patient/26b8f4f5-441f-481e-b50a-0cd265df4f08 in reference fields patient,performer of resource Procedure/16b495e0-c8d7-4ea4-8805-ac9a9498321c"
          }
        ]
      },
      "search": {
        "mode": "outcome"
      }
    }
  ]
Goal:-

"entry": [
    {
      "fullUrl": "https://sfp-proxy16248.azurewebsites.net/fhir/Goal/3cfadb39-d3b2-4efb-b9e7-504c6dd529d0",
      "resource": {
        "resourceType": "OperationOutcome",
        "id": "5a14286b-d346-4222-840f-9a3a626d6516",
        "issue": [
          {
            "severity": "warning",
            "code": "forbidden",
            "diagnostics": "Could not find Patient Reference Patient/26b8f4f5-441f-481e-b50a-0cd265df4f08 in reference fields patient of resource Goal/3cfadb39-d3b2-4efb-b9e7-504c6dd529d0"
          }
        ]
      },
      "search": {
        "mode": "outcome"
      }

**Comment by Kedar782** [comment]
@sordahl-ga 
I created separate issue for errors of procedure and goal resource.#82 
https://github.com/microsoft/fhir-proxy/issues/82

**Comment by vohuythao** [comment]
Hello @sordahl-ga ,

I met the same problem with @Kedar782 

Still not pass for Goal, Observation, Procedure
