### ISSUE TITLE
Cannot pass Inferno 7.2.05 test, get 500 error "export operation failed for reason: Unknown Error"

### ISSUE THREAD

**Issue by vohuythao** [microsoft/fhir-proxy#83]
Hello,

I run the Inferno test for Multi Patient.
The test 7.2.05 is failed 
![image](https://user-images.githubusercontent.com/14121587/204553439-a127fa78-d4ed-46b6-9e17-bbe869d4d200.png)

The last API call is get 500 error, more details

![image](https://user-images.githubusercontent.com/14121587/204553643-45636b2c-e961-46a6-9f18-12262fc9af60.png)

Check the log in FHIR proxy, function name "ProxyFunction"
![image](https://user-images.githubusercontent.com/14121587/204554333-c5811b9b-3d77-49a6-8d97-e8863d73f105.png)

This is unknown error

I check the export storage account and see there is ndjson file in blob container

![image](https://user-images.githubusercontent.com/14121587/204557101-1901f344-de5a-48d2-8d09-a162fffcf56a.png)

If you guys has any guidance or troubleshoot direction, please let me know

Thank you

**Comment by Kedar782** [comment]
@vohuythao 
Have you created a Group resource on the server?
If not please create a group resource and mention 2 patient IDs in the member field.
You need to mention this group resource id in the inferno before executing test 7.
This is my group resource. You can use this just change the Patient ID you want to use for export.

{
                "resourceType": "Group",
                "id": "abc08f6d-e822-4c80-8237-b52c2e7f515b",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-11-23T17:00:39.138+00:00"
                },
                "type": "person",
                "actual": true,
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/26b8f4f5-441f-481e-b50a-0cd265df4f08"
                        },
                        "period": {
                            "start": "2014-10-08"
                        }
                    },
                    {
                        "entity": {
                            "reference": "Patient/6b0ad32c-eb5d-4db1-81bc-000369b9a1f5"
                        },
                        "period": {
                            "start": "2015-04-02"
                        }
                    }
                ]
            }

**Comment by vohuythao** [comment]
Hello @Kedar782 

Thank you, it would be great if you can send me the batch bundle for above Group, I am not familiar with FHIR data

Thank you very much

**Comment by sordahl-ga** [comment]
There was a configuration step omitted in the documentation which is in this commit:
https://github.com/microsoft/fhir-proxy/commit/d2fc705d8701168a7de215071ab23fadd240dd0c
Please execute the missing step to set the FP-EXPORT-STORAGEACCT this should resolve the 500 error.

**Comment by sordahl-ga** [comment]
> Hello @Kedar782
> 
> Thank you, it would be great if you can send me the batch bundle for above Group, I am not familiar with FHIR data
> 
> Thank you very much

The Inferno Website offers example data and defines the data you need to be on the FHIR Server as the document states this does not cover FHIR Data requirements

**Comment by Kedar782** [comment]
> There was a configuration step omitted in the documentation which is in this commit: [d2fc705](https://github.com/microsoft/fhir-proxy/commit/d2fc705d8701168a7de215071ab23fadd240dd0c) Please execute the missing step to set the FP-EXPORT-STORAGEACCT this should resolve the 500 error.

It is not working even after following this step. I'm still getting the 500 error.

**Comment by vohuythao** [comment]
Hello @Kedar782 

I can pass 7.3.03
![image](https://user-images.githubusercontent.com/14121587/204776986-2e1c483a-9b5e-4a1b-a7e6-92acb7b75780.png)

If you follow the new guideline, add FP-EXPORT-STORAGEACCT = connection string of export storage account
in the proxy function app settings

![image](https://user-images.githubusercontent.com/14121587/204777416-6e35e904-8286-4539-9602-9c9be1ef98f1.png)

Hope this can help you to pass this

**Comment by vohuythao** [comment]
Hello @sordahl-ga @Kedar782 

Thank you for the new commit, it fixed all the Goal and Procedure issue.

I don't know why but i still not pass the 4.18.05

![image](https://user-images.githubusercontent.com/14121587/204778329-fa8e42fc-6e98-414f-b5bd-4cb944442cc9.png)

With the Provenance issue

"severity": "warning",
            "code": "forbidden",
            "diagnostics": "Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields target of resource Provenance/6368d1b9-f765-9495-acfc-4b0c8d11db3e"

I already deploy new version of proxy
![image](https://user-images.githubusercontent.com/14121587/204778611-eebc2153-2745-418b-ac57-febd47236f18.png)


Do you have any hint?
Thank you

**Comment by Kedar782** [comment]
@vohuythao 
Please add a target element in your provenance resource( id 6368d1b9-f765-9495-acfc-4b0c8d11db3e) with a patient reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2

**Comment by vohuythao** [comment]
@Kedar782 , have you passed the 7.3.03, error 500?
